### ISSUE TITLE
jobsplus.events.EventKeyInput.onKeyPress crash | 1.18.1 v0.2.6

### ISSUE THREAD

**Issue by ghost** [DAQEM/JobsPlus-Archive#3]
Issue: Upon pressing V or trying to rebind the vein miner control, a crash occurs.

Crash log: https://pastebin.com/KkpjuGwE

MC version: **1.18.1**
Forge version: **39.0.79**
Mods used:
Jobs+ **v0.2.6**
JEI **v9.4.1.100**

**Comment by PapaSteeni** [comment]
I'm confirming the bug, no pastebin as it is exactly the same as the one provided above. Game crashes when using the "v" key. Even before joining a world . (It crashed with the exact same crash log, when I was trying to paste "ctrl + v" my servers IP adress). Trying to reassign the keys so that "v" is no longer being used works, but the game still crashes if you use it for e.g. pasting, or while typing in chat. Removing Jobs+ did solve the problem.
I'm using it as part of the Medieval Minecraft (1.18.1) Modpack for Forge on Forge Version 39.0.76

**Comment by DAQEM** [comment]
The newest version of the mod should fixed this issue.

**Comment by PapaSteeni** [comment]
Works flawless now...Thank You!
