### ISSUE TITLE
Jobsplus crashes game

### ISSUE THREAD

**Issue by Polter098** [DAQEM/JobsPlus-Archive#56]
when starting the launcher your mod crashes the game for me I will also try to provide you with the latest game log

**Comment by SrRapero720** [comment]
**CRASH ALSO**
Probably its caused by Rubidium (because come from Mixing or not). But error is f_xxxx.getName() is null so idk
FORGE: 40.1.85
MC: 1.18.2
MOD: jobsplus-1.18.2-0.8.2.jar


CRASH REPORT: [crash-2022-12-08_14.52.22-client.txt](https://github.com/DAQEM/JobsPlus/files/10189419/crash-2022-12-08_14.52.22-client.txt)
LOG: [2022-12-08-1.log.gz](https://github.com/DAQEM/JobsPlus/files/10189421/2022-12-08-1.log.gz)
DEBUG: [debug-1.log.gz](https://github.com/DAQEM/JobsPlus/files/10189423/debug-1.log.gz)

**Comment by aNinjin** [comment]
> **CRASH ALSO** Probably its caused by Rubidium (because come from Mixing or not). But error is f_xxxx.getName() is null so idk FORGE: 40.1.85 MC: 1.18.2 MOD: jobsplus-1.18.2-0.8.2.jar
> 
> CRASH REPORT: [crash-2022-12-08_14.52.22-client.txt](https://github.com/DAQEM/JobsPlus/files/10189419/crash-2022-12-08_14.52.22-client.txt) LOG: [2022-12-08-1.log.gz](https://github.com/DAQEM/JobsPlus/files/10189421/2022-12-08-1.log.gz) DEBUG: [debug-1.log.gz](https://github.com/DAQEM/JobsPlus/files/10189423/debug-1.log.gz)

"rubidium_extras" seems to be the reason you're crashing. 
I am running Rubidium with Jobs+ and I have yet to run into any issues.

For future reference, the log file you uploaded would be of no help to anyone. The log file people use is called "latest" and is located in the logs folder.

**Comment by SrRapero720** [comment]
log i send is lastest.log of crash, but i run again minecraft so lastest.log is replaced for a new lastest.log and oldone get GZIP so its the right lastest.log file and right debug.log file (from crash)

**Comment by aNinjin** [comment]
> log i send is lastest.log of crash, but i run again minecraft so lastest.log is replaced for a new lastest.log and oldone get GZIP so its the right lastest.log file and right debug.log file (from crash)

Your latest log says the following (Assuming this is the log that was generated when you crashed):
Mod §ejobsplus§r requires §6jei§r §o10.2.1.283 or above§r
§7Currently, §6jei§r§7 is §o9.7.1.255

![image](https://user-images.githubusercontent.com/106577745/206576950-22155a6f-71c1-447f-8c10-743b8ad39ae5.png)
Since JEI is in Beta, it will not prompt you to update unless you manually go to the version and do it yourself.

**Comment by SrRapero720** [comment]
that solve it. thanks
